apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdemo1gh2
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tdemo1gh2
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1gh2
    
